---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1sg9nlhre5hwe75xdh3qrdg0dtcy4s5haa4dn3muf238c3sq7fcvs3anww7"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1sg9nlhre5hwe75xdh3qrdg0dtcy4s5haa4dn3muf238c3sq7fcvs3anww7"
