---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age167e03guwxs3pwlgywcd2jsmssn8t4jy29pha0szwzjaj57at0gkqjaljzy"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age167e03guwxs3pwlgywcd2jsmssn8t4jy29pha0szwzjaj57at0gkqjaljzy"
