apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:EoXSePBJmC4DueztJfKeseH8gieJNsva/lyDWtqghEH9bF8B,iv:14IxhWMHIjjUpWWjyH0YMBAHKMQp5Yq8DUUmDBJtzv0=,tag:hGWi66QQWPhD/c/K4SwgCA==,type:str]
    credentials.json: ENC[AES256_GCM,data:QxjO9GWAEwtvpzFHsgIOYQG8Z3L3I4Wd4gLLlmksKgnA6pD6s1K4pxIMdNY0iCahXQNLKh8z2aGWgijnNTgwNWCkcO9EevBV/opACsa40LDwN9L+s2r0XEo38ac51p/fC/DufafYoxlLNE3pgQM1clZ8ugk/bAUQOvke5ns0WCmreQPITBcxlo9TLEcizTwNvsG6+D2sy1tS2wVuiM0W+7m49mZ1cko5RQiOIg6GVA==,iv:O88Vt1ajFOtYxrKlzw+pPXru3aMOGlP1XZVUq922Rtw=,tag:tU6XLVGckzDI36TQ/6JVNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167e03guwxs3pwlgywcd2jsmssn8t4jy29pha0szwzjaj57at0gkqjaljzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL2F1L2RwbTJMNTF4eHVJ
            WEovYnlLZFBYRW1wUmhCUjQ1VGdWcUdaL3prCi9KUkRCV3preHJJdWRLZU13bkR1
            eW1qVXNNSzIydUNkdkhySVNndFphNFkKLS0tIDU4cmRmcmxRTXowbmhwZjhOcmls
            a0F1cm5RUGJBRU5PMEJFU3BicUNPVDAKz/JNEYcHJp5A2mYQFy/gc1mgzYlT1Rhh
            l4jCKgwmbPog9Dunu26k3ypQuP4baINiBSynywMwp6LDoYOP8o0R6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T23:00:34Z"
    mac: ENC[AES256_GCM,data:zP84WNkRqdUSn489d98kbSme/tCrbmqIMV4chLvX5DW9EXtCKavx/FynxXOWA545h9R+FVyMB8zISwREZR+BOBjPtBf77ya99HeciYpSQCJxE3HEP+bZtMhgzo4opuOsx1HDbTEwKih7biuoCrnrJzPeFJULGwJAdQz/ENs3kmw=,iv:inRt8hL0ptCz3+nQJHTsh3O135tcz85cF2/W7S95w7c=,tag:bEoii6/RP1Ll2odqQSuUcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
