apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2P2gBaEsla5/qEhwf5pKVc5c6eMxB1kW,iv:4319eS8Pq6eV3d8fqYbLWMM6RvHYqrX9/TB7o1oAym8=,tag:VpInPyq4z6hUrubq0+/diw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qv4ftxvk42cvhgwg85q9su5cdsas3jcwkews27wnx8qlprgj9fhq7n970x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOHl2MlN6WTZQbStCOEVv
            ejgvZWppUVZxQW91WnpPZVUrQWVyT0hjWkE0CmNKMzlMUkVZYUNZMVNRcUdWS3Np
            aE9VSS9mRkc5ekJsZVNwUzlPSk5kZzQKLS0tIEx4WWtPN0dXNndMRmxHb0twSFNF
            UWE3S1ZvbDB1di9Ub1ZhcjNOTGhaWnMKCwkQm99ht4QLiChCsPBa2gpENIDFL7Zw
            YEyZfdj/i3x9y288XxGwvz0sKCxBAiLnxIekGz+Ib74CPMHnnexYOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T03:19:55Z"
    mac: ENC[AES256_GCM,data:Wg6sye50TTiRqC70d7CF8Hh9QNF+V7Nuvhrccn4WfozY07ru9ze3P2tZxTa9B3VM7ddrzB/pZL1KBSq7LcFa02IMxx2z3u0GvI2bJyXqAbL9Wa318pXjDW3wht83V1hP03Kf8OuKenMW3gg3olQzXbJlIVIlz2mWNIn+dMtrP6c=,iv:1YumsabA/2Edeooa5Pn1lcXWZ+azcgnEZX4OLyoFHrw=,tag:6XKQKMdxdJMFhROjBIxlJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
