apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:idKQEf5+Js2yuaYqP/0UCmnVvLLCQylXl0XTl9Dmn/DNSflWG2Z2+A==,iv:7zWJ7wJiY56jkpsE21khcd4EvAz2vr5eY/aVwFVdH4k=,tag:K1QnTn8YN60j06SV75paCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qv4ftxvk42cvhgwg85q9su5cdsas3jcwkews27wnx8qlprgj9fhq7n970x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTVcyZFVrSGZtalozY1Bx
            cWg5VGRCODBCUzJmQVpueXdCRWFtem9NM2lJCi91Yk82S1o5RW51dTNCZm8rTUFD
            SGVSSHg5TGt6LytYVmg0Sng4akM3V28KLS0tICtDQUZIREJWMDdUR083VXpRd1E2
            L0c3WE1oYVAxUXRlTU5kdjRXYm54TDAKBydxFjj5Sez/1aW9GbdUfAEZlWPt9IxP
            HKc6IQ76//+q5aNYcgiJv1sWPdY4pNi9pMU/tRT3XUArcYrHZ9L1rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T03:19:55Z"
    mac: ENC[AES256_GCM,data:e/OaGSJG1rqduOZSLNR/ie79lCdyCi8aopy7gbOpkozY8267dIENES4Y2QrrdkJDyCzDNt8Dt/k8jVgmEzkdTdpnDkjiuK6w3ltuS55kSy+7sQBjglKoLsahI/uSHKXCbhThuyUaNaFA9btOR1grckjkEq67nG8ABiweKoDzsDs=,iv:S7scLKGVmLufU5arfwvi/8t7Ej/KHeP+Na1Daf1ClMU=,tag:PW+rBLusyTQUSPN3AjMo9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
