apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:cPj555iAU/lGDjX2iQIOMfipjfHm5BlGQyLHc5xmUbGiqYWEWslXjVntYoHvfkenQ8pQAsM7mbd7qgzF,iv:oFJXEn96Ood1LUtzelO/wNeAt8pY1lPIN02U1VfFefs=,tag:YfjweEq6Es1q7ijXVoSekQ==,type:str]
    username: ENC[AES256_GCM,data:yUfKx/w=,iv:t98cyHK+1wUI+BzmSrovqJvMMiJYBij66WyU2v+dl+A=,tag:oWuteRWNemC/GCSYwoRmew==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qv4ftxvk42cvhgwg85q9su5cdsas3jcwkews27wnx8qlprgj9fhq7n970x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTXk1bFZrYnNxNURuaHZM
            eGNidFFTRmJOeWJKZVVMM2Q3bENRZnhBSTJnCkpZM0NzYWxhbWYxejh1dTMrQkNn
            WmxNSXFKdVpOdDhNZ1dlQW1lRjdjWFkKLS0tIHhadVBUbGRpNXJVR0Q0NFpjMUU0
            Umw5OUpaYU1EZ1pYVEJWMm5wSzVnb1kKj1+FbF6UZWdWkONLuDo+NyLekqM0nr20
            CW/7UgjxJNMiGjshNkJZdvBdirGGIz2KdFhIUrAafYI5wQDbm1c+Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T03:20:09Z"
    mac: ENC[AES256_GCM,data:JBwedh5eo1FVSqmsClLMc5mr5X7t06wPfXVE1/J0lRG72nqYArnXIq8CyEZPzdTSf3ALP2Huilh6mQvjJ+zJz3zEUhXH4DFPRSLLOANjjKtpxOQ9kk5F0rxexVlhLPtDQ2n6Z1kzge4BrSU6/IAQYXss0VGZN3PXgv1T4zRs8Og=,iv:kZjGdS2f7LOkMAnI9PhQZTBuhK/P++FCC0zMk/sYdq4=,tag:BXX25bqogSubdirjQmYcEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
