apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:mc2i5BYTsr15Duzn,iv:VHitEPk9MKmDUBLiwjwIL3F01irytjsHkgZhE5k+6eY=,tag:C4IbvtYbWbAmRhmt6869OQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:k7YE282T1qOh7YeMxYTY3jLZrnWgoLclaxa/PEbpW7inzcXx,iv:L/hpkdhibQYJJTgbRMY8rmI0Y5QIhqEtxyv3fR2q0BE=,tag:S6dRs5BDF8zRiwUzI2tcKg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:cQAQ74DdVOp/,iv:5+5T++GlU19MF9Ias1Y2BcULYNY1Oq1Dj06FZnOSYBc=,tag:Th0u+UV88tb26yd55IT/oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qv4ftxvk42cvhgwg85q9su5cdsas3jcwkews27wnx8qlprgj9fhq7n970x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNmxYZEwzczNSVFJiU1RF
            bGtTb1QreEtrVmMrb2xWeklsTG8vMDNlNmlRCkRhakNseURrWllCNlZNdU1YWUps
            b1BWbStyQUpqK3pkMUVOdEZIVDYzUW8KLS0tIGhRbit4MzRKUEN4VFI1S1JPd3R6
            Y2lZa0NzbTRRNm5XMXhDVndYVC9Ha2MKIJgx3LBO3M/YVuJkcy7fD8o8aah/Ptop
            83efM/YHWbHkJ456wSsPElAsY5Pm+VQwW2KWdcgGvnFoDlDIb1E7Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T03:19:56Z"
    mac: ENC[AES256_GCM,data:xwtPLF6Bc70gIisOenQBb8vK74KT2X2msyYgHyLZIXIt0CzlbP5wMch+S0SP/TQbj/QD/dqb8R0b2rPOre4Hxy71EZZUEKr2RbIDVxxoj6YQHVdHlsgdeC9syXsILpT6EFi4MpMxqWemwgRE2yEpMjUPMDjVvBgFv/xpcdetaUY=,iv:qTRU1rsJwjTGhMXAO40QW7OP9adgdiAEKVyQZZr3K80=,tag:UY3mwXZ4H7g0hQcUCmY5Yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
