apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:k/GXia2Ei605Gp4xWaoVO1voutn8OCvD/IgghDHmk800MX1hdk9AE64MNcklYbfyEKQuck9+U7+3MYveRahK98gNFB+wy5lDjH+q7DyC3nAUxHn9KCUPG71et/SWgg==,iv:ifcbUq1NKRBfWIoA3dPKcKpRX1J3m4Yi24pb7VuLz8w=,tag:ywOQUoRgBLt/oG/1vieKGg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:rORKYtWnu8qO,iv:mkHYufYLYr6AsBLChqROmxgz7flFwTU+U44CxTH/w4s=,tag:R8RVTfKSUgbNl3+T5yzM6w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/FtnXWJc3Y6a3wQV,iv:Ji/9m3jdE8xQdTftGE/NKRbt7BKFYBmZRh2RVU/WDw8=,tag:oxBbnbQHk0IjWzMBLdNDNg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xBEf2jngVkEs5fi2T08dfZEDOzLNy0EMDdM0fkOzpuDEA1aa,iv:X/ZQbDZ+ZIwrDMvUzGY2aeZf7yKAy+GKBiZWlym/6ow=,tag:vt12v/rvvab/WS5MasombQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167e03guwxs3pwlgywcd2jsmssn8t4jy29pha0szwzjaj57at0gkqjaljzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUzlLTFhwZHZJbFZPZW11
            UlUyVkE1MjRhMm9hUlJGZW9Pc0tRYWtQejBZCm1ncGI1QmtldUU0ZUwxSVdYd2dT
            eEE1cGJNNFBCTE1WV05CVGQ3OERsVGMKLS0tIDFRV1FnUDZ3azIvN1kyTWNYdTdE
            WTBWeTY0dGVzcm4wL01hM0o4SS9nU3cKSbCBfGrXl3lblWBXwaJMuUduxeaPF+IJ
            G1qYnSzuQOuU1PcB8+qrJvVsYiD6Zn+w80T6mHftMpqPgHuTgwAQmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T16:44:23Z"
    mac: ENC[AES256_GCM,data:MbEntUTBEYr57reIxQfpGHWdxEjRb0JF8Bg1NjmNae8LIiocNfHX9cdXwJoDYduQI0FRztIh3XUTyRCHTpFFjgHU+oLEEkYlLKCME3/0UT0lGyyYEchibSB89nLwXqktPvzQnj+2IIS/CnYepIs2j/5un03OZ+V2f9DN6Zcpb54=,iv:RkvU4xTXhBgsHltVlvGMO+S1extGpYXP14m7PyYVhzk=,tag:p4Cnd5Lx06nQnD1Zm6LVbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
