apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:jLXblYCdtI/G4SeHTk4+PdNTKaJZvja2vR6mI2BTOFGlF0l4,iv:I4B5Y4harLewI+lRGo1x9RjATx8tWr3R/avFNGouIAw=,tag:Llwyp4pdACgRawkHhkSyLQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:TSH1Kg4/lL27V42sW2k8PHzc7BpkumJkTYtgAKC83whrp3QHnjoLQlgPI6z9ML1mj9Bh/qhh4Z/EbSKFdvLSy0TW+6qFVhjbttiCvJ/AUNTN0n3uocsOc4W0vJsox6+ER120HLLkNwzamhkUdo3YJzvpFH6OUaK3oAZZccVGNSxNTlF85QiLjv1e/1tBv7IWYr9J9dRoB4MO0iud7NlKL/V94//Nhrm0qjXKzgGtIA==,iv:LtCTL70e7Vs1tbDPfIYBzBviL8bVtl3kOv2QXM3Zjbc=,tag:D4KLR0hFqd4KqOZ1NEG/1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qv4ftxvk42cvhgwg85q9su5cdsas3jcwkews27wnx8qlprgj9fhq7n970x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUVk1UWI1Y2xyNkJiVVVD
            QVFLS205cjFvNndpNWdFaVZZZ3p3SWJ1M2hrCkJQREhkQUdyMDJxd1llaUVaV2Zi
            MHFsMHNqMzhsVlovL3pMZWhzNlhkRWMKLS0tIFR1bEtGQTFidnZ6SWRuSGRRc1JV
            RUJIUEwxSURscUhOaE0rQ2NNRTBvWWcKws6dlluC6nDs00WOUjHcfSAwgkoK/xpF
            Kh7qesanTk5NQLY/famnfftARRHatmtxMQ9d016vZr2CvuIxdI2pIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T03:19:55Z"
    mac: ENC[AES256_GCM,data:UM4SbmRC8LGfwT9mHmTMhxHvhj69/vCWB7yxEaqKa4XyQ9Cn8CIJ9CbvIrfN5ZlGtu6u3IXlDsQf8McyBj1xo8lw152qCCniA1WD/4mFzle9Z2cN3jkHgZ+bOeaFTgyU+SIQPMk/qlz+pC8gx3jKZFEdwRiGmuPuB786dMaDN/0=,iv:kzjc5lRjGqUrYfeKLqqqqARp5tSek8m0a9c35v7h74I=,tag:ekZsUFqYfY2W5f2boqMIWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
