apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Qb12bHT0TXzMIbpFJhGngvrAKSVe6Yp64oc5kTtQjU8=,iv:dFkU9t5KXCCJdFqM0dLEdP+qdWN3ZEWFboqmrqQnjtM=,tag:9/XoqWASZ22MDejyIODR9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sg9nlhre5hwe75xdh3qrdg0dtcy4s5haa4dn3muf238c3sq7fcvs3anww7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5N0QvVmd2UXIrVlZ2alNv
            SzFaUm9zRXMxTTNGQmVJWWlScEVmMDY0ZlFJCmdrOENNM1Vxb2ZCamJqeXc5MkVz
            TVBRZzRSSEpwU0EyYW5MZ1pQdkVjQWMKLS0tIDJheVlnTTBwV0JDYlNVNXV6NFg5
            aENXY3cydXY2T0Qrbk1IMUpFTFl6elUKbG4hXvxUylfY74OPnMglmZk8fZ9FJkWr
            8ySoHtloF0DuZ5rzweeoQn4evy7ays7byfSkaZRcdY6tc8zVsB4oQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-09T02:50:32Z"
    mac: ENC[AES256_GCM,data:Q8gBdu622iZjU4Y6+za4hFbFEqUY+Gjm7avZsZY6fU5PxJHiBxebHwDOJ9ktzI0YbdWmH0kbdo9ngRj12O8kSdbJyCHd8UNqChV53gjlry9Kmb2wl7jeVcCO2KJdCnKD3b+5HarzMHAly3jl8jMMjDGBQT1BGCC9BiE3KJYq4Ws=,iv:bupUh3tRLcrmnzH8Y8eVQYVLcf3S4Eb+gUGlLrLZp7s=,tag:gU5VKc2ZWkBq4JrRbLKl1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
