apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:GtiaB0oAH2hjKXqL4tWPo6qZf3WXBGocNPfQZ7LM1LjZCGwjlZ8Irg==,iv:i28boQRV6jAAuiirybyPBxmVRirtgEe34v2oddNO+0s=,tag:/VTObp4woXOFrdj0GIsnlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167e03guwxs3pwlgywcd2jsmssn8t4jy29pha0szwzjaj57at0gkqjaljzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST2lNUFBuUFFPdE9zcTB1
            OTVkc2tKRHZZaUI5UWdvSE1JTXBSUjdkUkNJCjFFVmQ4MTZsSTBhaTNTZ2l5dGFB
            U2RjMGRKckZnekcyWmdEdzlTeE5UMUUKLS0tIFIwd3BlSmcvNWpOMmNhWFM5TDBq
            MEJzNUJVbTJsWFJhUy96YXB0TDVKUGMKs8fL0Xcaw6n2t4/+P7Ug36mkax9q1vtG
            vqQtFEWVuWyMnJnTqZgivDR67G5Fitzu4PzmE3DhDxUk2lDCB70hpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T16:44:23Z"
    mac: ENC[AES256_GCM,data:qky/pVlHGace/mERV2hNxbVo14D7+KJMJalGpqhMf4XW4NfSQqOAFMJW128UXs/vkk6Ze/OCsyCWseSlOtL0cprtaaoJj5tPZJnCD6gBGLb5LukubN4QGePMIihQvNJ7nPOq4rFa7C369t1zuFRJ1iboP4b8B8Ps2k2Q6O99ltw=,iv:m3H2kngdRWaebGF3xFt31arf8Vgsh5/fdttZIP6n2fQ=,tag:Au0tAsLQ0RE6r5jB5j0m7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
